In [92]:
import pandas as pd
import numpy as np

ratingsAll = pd.read_csv("ratingGrid.csv")
dataArr = ratingsAll.as_matrix()
users = pd.read_csv("users_avg.csv")
movies = pd.read_csv("movies_avg.csv")

In [93]:
import copy
from sklearn import preprocessing
userInfo = users.copy()
del userInfo['Zip-code']



#genderArr3 = pd.get_dummies(genderArr, prefix = 'G')
#print genderArr3
userInfo = pd.concat([userInfo, pd.get_dummies(userInfo['Gender'], prefix='G')], axis=1)
userInfo = pd.concat([userInfo, pd.get_dummies(userInfo['Age'], prefix = 'A')], axis = 1)
userInfo = pd.concat([userInfo, pd.get_dummies(userInfo['Occupation'], prefix = 'O')], axis = 1)

del userInfo['Gender']
del userInfo['Age']
del userInfo['Occupation']
userInfo.head()

,UserID,Average,G_F,G_M,A_1,A_18,A_25,A_35,A_45,A_50,...,O_11,O_12,O_13,O_14,O_15,O_16,O_17,O_18,O_19,O_20
0,1,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,3.703125,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,3,3.900000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,4,4.100000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,3.187817,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [94]:
ratings = pd.read_csv('ratings.csv')
del ratings['Timestamp']
ratings.head()

   UserID  MovieID  Rating
0       1     1193       5
1       1      661       3
2       1      914       3
3       1     3408       4
4       1     2355       5

In [95]:
training = pd.merge(ratings, userInfo, on='UserID', how='outer')
training.head()

,UserID,MovieID,Rating,Average,G_F,G_M,A_1,A_18,A_25,A_35,...,O_11,O_12,O_13,O_14,O_15,O_16,O_17,O_18,O_19,O_20
0,1,1193,5,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,661,3,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,914,3,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,3408,4,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,2355,5,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [96]:
movieInfo = movies.copy()
del movieInfo['Unnamed: 0']
del movieInfo['Title']
genres = ['Action', 'Adventure', 'Animation', 'Children\'s', 'Comedy', 'Crime',
          'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
          'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
for genre in genres:
    movieInfo[genre] = np.zeros(len(movieInfo))
    
movieInfo['numGenres'] = np.zeros(len(movieInfo))
for i in range(len(movieInfo)):
    genreString = movieInfo.ix[i]['Genres']
    genreArr = genreString.split('|')
    count = 0
    for j in genreArr:
        if j in movieInfo:
            movieInfo.ix[i, j] = 1
            count = count + 1
        else:
            print i
            print j
            count = count + 1
    movieInfo.ix[i,'numGenres'] = count
movieInfo.head()

,MovieID,Genres,Average,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,numGenres
0,1,Animation|Children's|Comedy,4.146846,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
1,2,Adventure|Children's|Fantasy,3.201141,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
2,3,Comedy|Romance,3.016736,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
3,4,Comedy|Drama,2.729412,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4,5,Comedy,3.006757,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [97]:
userMovies = users.copy()
del userMovies['Gender']
del userMovies['Age']
del userMovies['Occupation']
del userMovies['Zip-code']
for genre in genres:
    userMovies[genre] = np.zeros(len(userMovies))
userMovies.head()

,UserID,Average,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,4.188679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,3.703125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,3.900000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,4.100000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,3.187817,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [98]:
movieGenres = movieInfo.copy()
del movieGenres['Genres']
del movieGenres['Average']
del movieGenres['numGenres']
movieGenres.head()

,MovieID,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [99]:
ratingsArr = ratingsAll.copy()
ratingsArr['MovieID'] = range(len(ratingsArr))
ratingsArr = pd.merge(ratingsArr, movieGenres, on='MovieID', how='outer')
#ratingsArr.ix[0] = ratingsArr.ix[0].fillna(0)
ratingsArr.head()

,0,1,2,3,4,5,6,7,8,9,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,5,0,0,0,0,4,0,4,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [100]:
ratingsArr.ix[:, genres] = ratingsArr.ix[:, genres].fillna(value=0)

ratingsArr.head()

,0,1,2,3,4,5,6,7,8,9,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,5,0,0,0,0,4,0,4,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:
import time
start = time.clock()
for i in range(1, len(userMovies)):
    ratings = ratingsArr.ix[:,i].as_matrix()
    for genre in genres:
        #print ratingsArr.ix[:,genre].as_matrix()
        product = ratings * ratingsArr.ix[:,genre].as_matrix()
        avgProduct = product[product != 0]
        if (len(avgProduct > 0)):
            avg = np.mean(avgProduct)
        else:
            avg = 0
        userMovies.ix[i - 1, genre] = avg
    if (i % 100 == 0):
        print i
end = time.clock() 
print (end - start)
userMovies.head()

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
114.159564461

,UserID,Average,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,4.188679,4.200000,4.000000,4.111111,4.250000,4.142857,4.000000,0.000000,4.428571,4.0,0.0,0.000000,4.285714,0.000000,3.666667,4.333333,3.666667,5.000000,0.000000
1,2,3.703125,3.500000,3.736842,0.000000,0.000000,3.560000,3.583333,0.000000,3.898734,3.0,4.0,3.000000,0.000000,3.333333,3.708333,3.588235,3.483871,3.733333,4.333333
2,3,3.900000,3.956522,4.000000,4.000000,4.000000,3.766667,0.000000,0.000000,4.000000,4.5,0.0,2.666667,4.000000,3.000000,3.800000,3.833333,3.800000,4.000000,4.666667
3,4,4.100000,4.157895,3.833333,0.000000,4.000000,0.000000,5.000000,0.000000,4.166667,4.5,0.0,4.333333,0.000000,0.000000,4.000000,3.555556,3.500000,3.333333,4.500000
4,5,3.187817,2.612903,3.000000,4.000000,3.833333,3.410714,3.285714,3.666667,3.096154,0.0,4.0,2.800000,3.333333,3.125000,3.100000,3.066667,2.846154,3.500000,4.000000

In [86]:
#userMovies.to_csv('userMovieRatings.csv')

In [ ]:
import time
start = time.clock()
for j in range(5):
    countArr2 = np.zeros(18)
    sumArr2 = np.zeros(18)
    #avgArr2 = np.zeros(18)
    for i in range(len(dataArr)):
        if (dataArr[i][j] != 0):
            for g in range(len(genres)):
                genreName = genres[g]
                if (movieInfo.ix[movieInfo['MovieID'] == i, genreName].item() != 0):
                    sumArr2[g] = sumArr2[g] + dataArr[i][j]
                    countArr2[g] = countArr2[g] + 1
    for g in range(len(genres)):
        if (countArr2[g] != 0):
            genreName = genres[g]
            userMovies.ix[userMovies['UserID'] == j, genre] = float(sumArr2[g]) / countArr2[g]
            #avgArr2[g] = float(sumArr2[g]) / countArr2[g]
    print j
end = time.clock()
print (end - start)
userMovies.head()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529

In [101]:
training['MovieAvg'] = np.zeros(len(training))
training['MovieVec'] = np.zeros(len(training))
training['Intercept'] = np.ones(len(training))
training.head()

,UserID,MovieID,Rating,Average,G_F,G_M,A_1,A_18,A_25,A_35,...,O_14,O_15,O_16,O_17,O_18,O_19,O_20,MovieAvg,MovieVec,Intercept
0,1,1193,5,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1,661,3,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1,914,3,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1,3408,4,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1,2355,5,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [102]:
tempMovie = movies.copy()
del tempMovie['Unnamed: 0']
del tempMovie['Title']
del tempMovie['Genres']
tempMovie['MovieAvg'] = tempMovie['Average']
del tempMovie['Average']
tempMovie.head()

   MovieID  MovieAvg
0        1  4.146846
1        2  3.201141
2        3  3.016736
3        4  2.729412
4        5  3.006757

In [104]:
del training['MovieAvg_x']
del training['MovieAvg_y']
training = pd.merge(training, tempMovie, on='MovieID', how='outer')
training.head()

,UserID,MovieID,Rating,Average,G_F,G_M,A_1,A_18,A_25,A_35,...,O_14,O_15,O_16,O_17,O_18,O_19,O_20,MovieVec,Intercept,MovieAvg
0,1.0,1193.0,5.0,4.188679,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725
1,2.0,1193.0,5.0,3.703125,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725
2,12.0,1193.0,4.0,3.772727,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725
3,15.0,1193.0,4.0,3.310000,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725
4,17.0,1193.0,5.0,4.038095,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725

In [106]:
training['UserAvg'] = training['Average']
del training['Average']
training.head()

,UserID,MovieID,Rating,G_F,G_M,A_1,A_18,A_25,A_35,A_45,...,O_15,O_16,O_17,O_18,O_19,O_20,MovieVec,Intercept,MovieAvg,UserAvg
0,1.0,1193.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725,4.188679
1,2.0,1193.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725,3.703125
2,12.0,1193.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725,3.772727
3,15.0,1193.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725,3.310000
4,17.0,1193.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.390725,4.038095

In [108]:
userMovies = pd.read_csv('userMovieRatings.csv')
del userMovies['Unnamed: 0']
del userMovies['Average']
userMovies.head()

,UserID,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,4.200000,4.000000,4.111111,4.250000,4.142857,4.000000,0.000000,4.428571,4.0,0.0,0.000000,4.285714,0.000000,3.666667,4.333333,3.666667,5.000000,0.000000
1,2,3.500000,3.736842,0.000000,0.000000,3.560000,3.583333,0.000000,3.898734,3.0,4.0,3.000000,0.000000,3.333333,3.708333,3.588235,3.483871,3.733333,4.333333
2,3,3.956522,4.000000,4.000000,4.000000,3.766667,0.000000,0.000000,4.000000,4.5,0.0,2.666667,4.000000,3.000000,3.800000,3.833333,3.800000,4.000000,4.666667
3,4,4.157895,3.833333,0.000000,4.000000,0.000000,5.000000,0.000000,4.166667,4.5,0.0,4.333333,0.000000,0.000000,4.000000,3.555556,3.500000,3.333333,4.500000
4,5,2.612903,3.000000,4.000000,3.833333,3.410714,3.285714,3.666667,3.096154,0.0,4.0,2.800000,3.333333,3.125000,3.100000,3.066667,2.846154,3.500000,4.000000

In [109]:
training2 = pd.merge(training, userMovies, on='UserID', how='outer')
training2.head()

,UserID,MovieID,Rating,G_F,G_M,A_1,A_18,A_25,A_35,A_45,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1.0,1193.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
1,1.0,661.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
2,1.0,914.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
3,1.0,3408.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
4,1.0,2355.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0

In [110]:
for g in genres:
    training2[g + 'a'] = training2[g]
    del training2[g]
training2.head()

,UserID,MovieID,Rating,G_F,G_M,A_1,A_18,A_25,A_35,A_45,...,Fantasya,Film-Noira,Horrora,Musicala,Mysterya,Romancea,Sci-Fia,Thrillera,Wara,Westerna
0,1.0,1193.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
1,1.0,661.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
2,1.0,914.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
3,1.0,3408.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0
4,1.0,2355.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,4.285714,0.0,3.666667,4.333333,3.666667,5.0,0.0

In [111]:

training3 = pd.merge(training2, movieGenres, on='MovieID', how='outer')
training3.head()

,UserID,MovieID,Rating,G_F,G_M,A_1,A_18,A_25,A_35,A_45,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1.0,1193.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,1193.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12.0,1193.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,15.0,1193.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17.0,1193.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [122]:
genresa = ['Actiona', 'Adventurea', 'Animationa', 'Children\'sa', 'Comedya', 'Crimea',
          'Documentarya', 'Dramaa', 'Fantasya', 'Film-Noira', 'Horrora', 'Musicala',
          'Mysterya', 'Romancea', 'Sci-Fia', 'Thrillera', 'Wara', 'Westerna']
start = time.clock()
for i in range(len(training3)):
    n1 = training3.ix[i][genresa].as_matrix()
    n2 = training3.ix[i][genres].as_matrix()
    n3 = n1 * n2
    n4 = n3[n3 != 0]
    avg = 0
    if (len(n4) > 0):
        avg = np.mean(n4)
    training3.ix[i, 'MovieVec'] = avg
    if (i % 1000 == 0):
        print i
end = time.clock()
print (end - start)
print training3.ix[range(6), 'MovieVec']

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000
213000
214000
215000
216000
217000
218000
219000
220000
221000
222000
223000
224000
225000
226000
227000
228000
229000
230000
231000
232000
233000
234000
235000
236000
237000
238000
239000
240000
241000
242000
243000
244000
245000
246000
247000
248000
249000
250000
251000
252000
253000
254000
255000
256000
257000
258000
259000
260000
261000
262000
263000
264000
265000
266000
267000
268000
269000
270000
271000
272000
273000
274000
275000
276000
277000
278000
279000
280000
281000
282000
283000
284000
285000
286000
287000
288000
289000
290000
291000
292000
293000
294000
295000
296000
297000
298000
299000
300000
301000
302000
303000
304000
305000
306000
307000
308000
309000
310000
311000
312000
313000
314000
315000
316000
317000
318000
319000
320000
321000
322000
323000
324000
325000
326000
327000
328000
329000
330000
331000
332000
333000
334000
335000
336000
337000
338000
339000
340000
341000
342000
343000
344000
345000
346000
347000
348000
349000
350000
351000
352000
353000
354000
355000
356000
357000
358000
359000
360000
361000
362000
363000
364000
365000
366000
367000
368000
369000
370000
371000
372000
373000
374000
375000
376000
377000
378000
379000
380000
381000
382000
383000
384000
385000
386000
387000
388000
389000
390000
391000
392000
393000
394000
395000
396000
397000
398000
399000
400000
401000
402000
403000
404000
405000
406000
407000
408000
409000
410000
411000
412000
413000
414000
415000
416000
417000
418000
419000
420000
421000
422000
423000
424000
425000
426000
427000
428000
429000
430000
431000
432000
433000
434000
435000
436000
437000
438000
439000
440000
441000
442000
443000
444000
445000
446000
447000
448000
449000
450000
451000
452000
453000
454000
455000
456000
457000
458000
459000
460000
461000
462000
463000
464000
465000
466000
467000
468000
469000
470000
471000
472000
473000
474000
475000
476000
477000
478000
479000
480000
481000
482000
483000
484000
485000
486000
487000
488000
489000
490000
491000
492000
493000
494000
495000
496000
497000
498000
499000
500000
501000
502000
503000
504000
505000
506000
507000
508000
509000
510000
511000
512000
513000
514000
515000
516000
517000
518000
519000
520000
521000
522000
523000
524000
525000
526000
527000
528000
529000
530000
531000
532000
533000
534000
535000
536000
537000
538000
539000
540000
541000
542000
543000
544000
545000
546000
547000
548000
549000
550000
551000
552000
553000
554000
555000
556000
557000
558000
559000
560000
561000
562000
563000
564000
565000
566000
567000
568000
569000
570000
571000
572000
573000
574000
575000
576000
577000
578000
579000
580000
581000
582000
583000
584000
585000
586000
587000
588000
589000
590000
591000
592000
593000
594000
595000
596000
597000
598000
599000
600000
601000
602000
603000
604000
605000
606000
607000
608000
609000
610000
611000
612000
613000
614000
615000
616000
617000
618000
619000
620000
621000
622000
623000
624000
625000
626000
627000
628000
629000
630000
631000
632000
633000
634000
635000
636000
637000
638000
639000
640000
641000
642000
643000
644000
645000
646000
647000
648000
649000
650000
651000
652000
653000
654000
655000
656000
657000
658000
659000
660000
661000
662000
663000
664000
665000
666000
667000
668000
669000
670000
671000
672000
673000
674000
675000
676000
677000
678000
679000
680000
681000
682000
683000
684000
685000
686000
687000
688000
689000
690000
691000
692000
693000
694000
695000
696000
697000
698000
699000
700000
701000
702000
703000
704000
705000
706000
707000
708000
709000
710000
711000
712000
713000
714000
715000
716000
717000
718000
719000
720000
721000
722000
723000
724000
725000
726000
727000
728000
729000
730000
731000
732000
733000
734000
735000
736000
737000
738000
739000
740000
741000
742000
743000
744000
745000
746000
747000
748000
749000
750000
751000
752000
753000
754000
755000
756000
757000
758000
759000
760000
761000
762000
763000
764000
765000
766000
767000
768000
769000
770000
771000
772000
773000
774000
775000
776000
777000
778000
779000
780000
781000
782000
783000
784000
785000
786000
787000
788000
789000
790000
791000
792000
793000
794000
795000
796000
797000
798000
799000
800000
801000
802000
803000
804000
805000
806000
807000
808000
809000
810000
811000
812000
813000
814000
815000
816000
817000
818000
819000
820000
821000
822000
823000
824000
825000
826000
827000
828000
829000
830000
831000
832000
833000
834000
835000
836000
837000
838000
839000
840000
841000
842000
843000
844000
845000
846000
847000
848000
849000
850000
851000
852000
853000
854000
855000
856000
857000
858000
859000
860000
861000
862000
863000
864000
865000
866000
867000
868000
869000
870000
871000
872000
873000
874000
875000
876000
877000
878000
879000
880000
881000
882000
883000
884000
885000
886000
887000
888000
889000
890000
891000
892000
893000
894000
895000
896000
897000
898000
899000
900000
901000
902000
903000
904000
905000
906000
907000
908000
909000
910000
911000
912000
913000
914000
915000
916000
917000
918000
919000
920000
921000
922000
923000
924000
925000
926000
927000
928000
929000
930000
931000
932000
933000
934000
935000
936000
937000
938000
939000
940000
941000
942000
943000
944000
945000
946000
947000
948000
949000
950000
951000
952000
953000
954000
955000
956000
957000
958000
959000
960000
961000
962000
963000
964000
965000
966000
967000
968000
969000
970000
971000
972000
973000
974000
975000
976000
977000
978000
979000
980000
981000
982000
983000
984000
985000
986000
987000
988000
989000
990000
991000
992000
993000
994000
995000
996000
997000
998000
999000
1000000
1797.20657193
0    4.428571
1    3.898734
2    4.333333
3    3.481013
4    4.144928
5    3.961165
Name: MovieVec, dtype: float64

In [128]:
training4 = training3.copy()
for i in range(len(genres)):
    del training4[genresa[i]]
print training4.columns.values

['UserID' 'MovieID' 'Rating' 'G_F' 'G_M' 'A_1' 'A_18' 'A_25' 'A_35' 'A_45'
 'A_50' 'A_56' 'O_0' 'O_1' 'O_2' 'O_3' 'O_4' 'O_5' 'O_6' 'O_7' 'O_8' 'O_9'
 'O_10' 'O_11' 'O_12' 'O_13' 'O_14' 'O_15' 'O_16' 'O_17' 'O_18' 'O_19'
 'O_20' 'MovieVec' 'Intercept' 'MovieAvg' 'UserAvg' 'Action' 'Adventure'
 'Animation' "Children's" 'Comedy' 'Crime' 'Documentary' 'Drama' 'Fantasy'
 'Film-Noir' 'Horror' 'Musical' 'Mystery' 'Romance' 'Sci-Fi' 'Thriller'
 'War' 'Western']

In [129]:
training4.to_csv('trainGenre.csv')
training4.head()

,UserID,MovieID,Rating,G_F,G_M,A_1,A_18,A_25,A_35,A_45,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1.0,1193.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,1193.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12.0,1193.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,15.0,1193.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17.0,1193.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [104]:
for i in range(20000,20010):
    userID = training.ix[i]['UserID']
    movieID = training.ix[i]['MovieID']
    total = 0
    #for genre in genres:
    n1 = userMovies.ix[userMovies['UserID'] == userID]
    del n1['UserID']
    del n1['Average']
    n2 = movieInfo.ix[movieInfo['MovieID'] == movieID]
    del n2['MovieID']
    del n2['Average']
    del n2['Genres']
    numGenres = n2['numGenres'].item()
    del n2['numGenres']
    n1a = n1.as_matrix()
    n2a = n2.as_matrix()
    n3 = np.sum(n1a * n2a)
    if (numGenres > 0):
        vec = n3 / numGenres
    else:
        vec = 0
    print movieID
    print userID
    print n1
    print n2
    print vec

3105.0
4473.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4472     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4472    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4472       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4480.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4479     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4479    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4479       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4482.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4481     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4481    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4481       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4483.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4482     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4482    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4482       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4502.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4501     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4501    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4501       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4505.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4504     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4504    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4504       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4508.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4507     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4507    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4507       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4510.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4509     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4509    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4509       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4521.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4520     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4520    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4520       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0
3105.0
4543.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
4542     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
4542    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
4542       0.0  0.0      0.0
      Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
3036     0.0        0.0        0.0         0.0     0.0    0.0          0.0

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
3036    1.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0

      Thriller  War  Western
3036       0.0  0.0      0.0
0.0